name: CI Checks

on:
  push:
    paths:
      - "**.v"
      - "**.vsh"
      - "**.md"
      - "**/ci.yml"
  pull_request:
    paths:
      - "**.v"
      - "**.vsh"
      - "**.md"
      - "**/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      VFLAGS: -no-parallel
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true
      - name: Install X11/GL development dependencies (headers and libs)
        run: v retry -- sudo apt install libgl1-mesa-dri xvfb libxcursor-dev libxi-dev libxrandr-dev freeglut3-dev
      - name: Checkout the gui module
        uses: actions/checkout@v4
        with:
          path: gui
      - name: Verify formatting
        run: v fmt -verify -inprocess gui/
      - name: Check formatting of MD files
        run: v check-md gui/
      - name: Check syntax of examples
        run: v gui/examples/_check.vsh
      - name: Check compilation of examples
        run: v should-compile-all gui/examples/

  compiling-with-prod:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    env:
      VFLAGS: -no-parallel
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true
      - name: Install X11/GL development dependencies (headers and libs)
        if: runner.os == 'Linux'
        run: v retry -- sudo apt install libgl1-mesa-dri xvfb libxcursor-dev libxi-dev libxrandr-dev freeglut3-dev
      - name: Checkout the gui module
        uses: actions/checkout@v4
        with:
          path: gui
      - name: Check compilation of examples
        run: v should-compile-all gui/examples/
      - name: Check compilation of examples with -prod
        run: v gui/examples/_build.vsh
